<?php

namespace Japode\Post\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * JPPostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JPPostRepository extends EntityRepository
{
}
