<?php

namespace Japode\Widget\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * JPWidgetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JPWidgetRepository extends EntityRepository
{
}
