<?php

namespace Japode\Region\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * JPRegionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JPRegionRepository extends EntityRepository {

    /**
     * Finds a region with its name
     *
     * @param string $name
     * @return JPRegion
     */
    public function findByName($name) {

        $qb = $this->createQueryBuilder('r');
        return $qb->where($qb->expr()->eq('r.name', ':name'))
                        ->setParameter('name', $name)
                        ->getQuery()
                        ->getOneOrNullResult();
    }

}
