//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.17 at 02:23:34 PM BRT 
//


package com.viglet.shiohara.wem.v8510.body;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * Type which represents a child node in the configuration space.
 * 
 * <p>Java class for configChildNodeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="configChildNodeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.vignette.com/xmlschemas/importexport}configNodeType">
 *       &lt;sequence>
 *         &lt;element name="inclusion" type="{http://www.vignette.com/xmlschemas/importexport}inclusionType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="variable" type="{http://www.vignette.com/xmlschemas/importexport}configVariableType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="node" type="{http://www.vignette.com/xmlschemas/importexport}configChildNodeType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "configChildNodeType")
public class ConfigChildNodeType
    extends ConfigNodeType
{


}
