//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.17 at 02:23:34 PM BRT 
//


package com.viglet.shiohara.wem.v8510.body;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *   ---------------------------------------------------------------------------
 *   - Name:  CT_adhocReferences
 *   - Desc:  Ad-hoc references associated with a ManagedObject.
 *   ---------------------------------------------------------------------------
 *   			
 * 
 * <p>Java class for CT_adhocReferences complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CT_adhocReferences">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="adhocReference" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="referenceName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="referentId" type="{http://www.vignette.com/xmlschemas/importexport}CT_id"/>
 *                   &lt;element name="metadata" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CT_adhocReferences", propOrder = {
    "adhocReference"
})
public class CTAdhocReferences {

    protected List<CTAdhocReferences.AdhocReference> adhocReference;

    /**
     * Gets the value of the adhocReference property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the adhocReference property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAdhocReference().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CTAdhocReferences.AdhocReference }
     * 
     * 
     */
    public List<CTAdhocReferences.AdhocReference> getAdhocReference() {
        if (adhocReference == null) {
            adhocReference = new ArrayList<CTAdhocReferences.AdhocReference>();
        }
        return this.adhocReference;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="referenceName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="referentId" type="{http://www.vignette.com/xmlschemas/importexport}CT_id"/>
     *         &lt;element name="metadata" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "referenceName",
        "referentId",
        "metadata"
    })
    public static class AdhocReference {

        @XmlElement(required = true)
        protected String referenceName;
        @XmlElement(required = true)
        protected CTId referentId;
        @XmlElement(required = true)
        protected String metadata;

        /**
         * Gets the value of the referenceName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getReferenceName() {
            return referenceName;
        }

        /**
         * Sets the value of the referenceName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setReferenceName(String value) {
            this.referenceName = value;
        }

        /**
         * Gets the value of the referentId property.
         * 
         * @return
         *     possible object is
         *     {@link CTId }
         *     
         */
        public CTId getReferentId() {
            return referentId;
        }

        /**
         * Sets the value of the referentId property.
         * 
         * @param value
         *     allowed object is
         *     {@link CTId }
         *     
         */
        public void setReferentId(CTId value) {
            this.referentId = value;
        }

        /**
         * Gets the value of the metadata property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMetadata() {
            return metadata;
        }

        /**
         * Sets the value of the metadata property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMetadata(String value) {
            this.metadata = value;
        }

    }

}
