//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.17 at 02:23:34 PM BRT 
//


package com.viglet.shiohara.wem.v8510.body;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *   ---------------------------------------------------------------------------
 *   - Name:  CT_channelInactiveFormatAssociations
 *   - Desc:  Defines Channel-InactiveFormat asociations for a channel entity.
 *   ---------------------------------------------------------------------------
 * 		      
 * 
 * <p>Java class for CT_channelInactiveFormatAssociations complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CT_channelInactiveFormatAssociations">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="inactiveFormatAssocData" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="formatId" type="{http://www.vignette.com/xmlschemas/importexport}CT_id"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CT_channelInactiveFormatAssociations", propOrder = {
    "inactiveFormatAssocData"
})
public class CTChannelInactiveFormatAssociations {

    protected List<CTChannelInactiveFormatAssociations.InactiveFormatAssocData> inactiveFormatAssocData;

    /**
     * Gets the value of the inactiveFormatAssocData property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the inactiveFormatAssocData property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInactiveFormatAssocData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CTChannelInactiveFormatAssociations.InactiveFormatAssocData }
     * 
     * 
     */
    public List<CTChannelInactiveFormatAssociations.InactiveFormatAssocData> getInactiveFormatAssocData() {
        if (inactiveFormatAssocData == null) {
            inactiveFormatAssocData = new ArrayList<CTChannelInactiveFormatAssociations.InactiveFormatAssocData>();
        }
        return this.inactiveFormatAssocData;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="formatId" type="{http://www.vignette.com/xmlschemas/importexport}CT_id"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "formatId"
    })
    public static class InactiveFormatAssocData {

        @XmlElement(required = true)
        protected CTId formatId;

        /**
         * Gets the value of the formatId property.
         * 
         * @return
         *     possible object is
         *     {@link CTId }
         *     
         */
        public CTId getFormatId() {
            return formatId;
        }

        /**
         * Sets the value of the formatId property.
         * 
         * @param value
         *     allowed object is
         *     {@link CTId }
         *     
         */
        public void setFormatId(CTId value) {
            this.formatId = value;
        }

    }

}
