//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.17 at 02:23:34 PM BRT 
//


package com.viglet.shiohara.wem.v8510.body;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *   ---------------------------------------------------------------------------
 *   - Name:  CT_segmentProfileAssociations
 *   - Desc:  Defines Site-SegmentProfile associations for a site entity.
 *   ---------------------------------------------------------------------------
 * 		      
 * 
 * <p>Java class for CT_segmentProfileAssociations complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CT_segmentProfileAssociations">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="segmentProfileAssocData" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="segmentProfileId" type="{http://www.vignette.com/xmlschemas/importexport}CT_id"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CT_segmentProfileAssociations", propOrder = {
    "segmentProfileAssocData"
})
public class CTSegmentProfileAssociations {

    protected List<CTSegmentProfileAssociations.SegmentProfileAssocData> segmentProfileAssocData;

    /**
     * Gets the value of the segmentProfileAssocData property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the segmentProfileAssocData property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSegmentProfileAssocData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CTSegmentProfileAssociations.SegmentProfileAssocData }
     * 
     * 
     */
    public List<CTSegmentProfileAssociations.SegmentProfileAssocData> getSegmentProfileAssocData() {
        if (segmentProfileAssocData == null) {
            segmentProfileAssocData = new ArrayList<CTSegmentProfileAssociations.SegmentProfileAssocData>();
        }
        return this.segmentProfileAssocData;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="segmentProfileId" type="{http://www.vignette.com/xmlschemas/importexport}CT_id"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "segmentProfileId"
    })
    public static class SegmentProfileAssocData {

        @XmlElement(required = true)
        protected CTId segmentProfileId;

        /**
         * Gets the value of the segmentProfileId property.
         * 
         * @return
         *     possible object is
         *     {@link CTId }
         *     
         */
        public CTId getSegmentProfileId() {
            return segmentProfileId;
        }

        /**
         * Sets the value of the segmentProfileId property.
         * 
         * @param value
         *     allowed object is
         *     {@link CTId }
         *     
         */
        public void setSegmentProfileId(CTId value) {
            this.segmentProfileId = value;
        }

    }

}
