//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.17 at 02:23:34 PM BRT 
//


package com.viglet.shiohara.wem.v8510.body;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EN_channelType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="EN_channelType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *     &lt;enumeration value="home"/>
 *     &lt;enumeration value="unassignedContent"/>
 *     &lt;enumeration value="archivedContent"/>
 *     &lt;enumeration value="applicationAssets"/>
 *     &lt;enumeration value="subChannel"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "EN_channelType")
@XmlEnum
public enum ENChannelType {

    @XmlEnumValue("home")
    HOME("home"),
    @XmlEnumValue("unassignedContent")
    UNASSIGNED_CONTENT("unassignedContent"),
    @XmlEnumValue("archivedContent")
    ARCHIVED_CONTENT("archivedContent"),
    @XmlEnumValue("applicationAssets")
    APPLICATION_ASSETS("applicationAssets"),
    @XmlEnumValue("subChannel")
    SUB_CHANNEL("subChannel");
    private final String value;

    ENChannelType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ENChannelType fromValue(String v) {
        for (ENChannelType c: ENChannelType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
