//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.17 at 02:23:34 PM BRT 
//


package com.viglet.shiohara.wem.v8510.body;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EN_objectType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="EN_objectType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="channel"/>
 *     &lt;enumeration value="configNode"/>
 *     &lt;enumeration value="contentType"/>
 *     &lt;enumeration value="objectType"/>
 *     &lt;enumeration value="preferences"/>
 *     &lt;enumeration value="programTask"/>
 *     &lt;enumeration value="project"/>
 *     &lt;enumeration value="roles"/>
 *     &lt;enumeration value="site"/>
 *     &lt;enumeration value="staticFile"/>
 *     &lt;enumeration value="taxonomy"/>
 *     &lt;enumeration value="workflow"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "EN_objectType")
@XmlEnum
public enum ENObjectType {

    @XmlEnumValue("channel")
    CHANNEL("channel"),
    @XmlEnumValue("configNode")
    CONFIG_NODE("configNode"),
    @XmlEnumValue("contentType")
    CONTENT_TYPE("contentType"),
    @XmlEnumValue("objectType")
    OBJECT_TYPE("objectType"),
    @XmlEnumValue("preferences")
    PREFERENCES("preferences"),
    @XmlEnumValue("programTask")
    PROGRAM_TASK("programTask"),
    @XmlEnumValue("project")
    PROJECT("project"),
    @XmlEnumValue("roles")
    ROLES("roles"),
    @XmlEnumValue("site")
    SITE("site"),
    @XmlEnumValue("staticFile")
    STATIC_FILE("staticFile"),
    @XmlEnumValue("taxonomy")
    TAXONOMY("taxonomy"),
    @XmlEnumValue("workflow")
    WORKFLOW("workflow");
    private final String value;

    ENObjectType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ENObjectType fromValue(String v) {
        for (ENObjectType c: ENObjectType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
