//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.17 at 02:23:34 PM BRT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.vignette.com/xmlschemas/importexport", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.viglet.shiohara.wem.v8510.body;
