//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.17 at 02:23:34 PM BRT 
//


package com.viglet.shiohara.wem.v8510.body;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="siteId" type="{http://www.vignette.com/xmlschemas/importexport}CT_id"/>
 *         &lt;element name="siteDescriptorId" type="{http://www.vignette.com/xmlschemas/importexport}CT_id" minOccurs="0"/>
 *         &lt;element name="siteLocaleDescriptorId" type="{http://www.vignette.com/xmlschemas/importexport}CT_id" minOccurs="0"/>
 *         &lt;element name="channelDescriptorId" type="{http://www.vignette.com/xmlschemas/importexport}CT_id" minOccurs="0"/>
 *         &lt;element name="channelLocaleDescriptorId" type="{http://www.vignette.com/xmlschemas/importexport}CT_id" minOccurs="0"/>
 *         &lt;element name="contentTypeAssociation" type="{http://www.vignette.com/xmlschemas/importexport}CT_siteContentTypeAssociation" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="adhocReferences" type="{http://www.vignette.com/xmlschemas/importexport}CT_adhocReferences" minOccurs="0"/>
 *         &lt;element name="acl" type="{http://www.vignette.com/xmlschemas/importexport}CT_acl" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.vignette.com/xmlschemas/importexport}AG_moAttributes"/>
 *       &lt;attGroup ref="{http://www.vignette.com/xmlschemas/importexport}AG_appSvcsAttributes"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "siteId",
    "siteDescriptorId",
    "siteLocaleDescriptorId",
    "channelDescriptorId",
    "channelLocaleDescriptorId",
    "contentTypeAssociation",
    "adhocReferences",
    "acl"
})
@XmlRootElement(name = "siteContentType")
public class SiteContentType {

    @XmlElement(required = true)
    protected CTId siteId;
    protected CTId siteDescriptorId;
    protected CTId siteLocaleDescriptorId;
    protected CTId channelDescriptorId;
    protected CTId channelLocaleDescriptorId;
    protected List<CTSiteContentTypeAssociation> contentTypeAssociation;
    protected CTAdhocReferences adhocReferences;
    protected CTAcl acl;
    @XmlAttribute(name = "vcmId")
    protected String vcmId;
    @XmlAttribute(name = "vcmStatus")
    protected String vcmStatus;
    @XmlAttribute(name = "vcmName")
    protected String vcmName;
    @XmlAttribute(name = "vcmLogicalPath")
    protected String vcmLogicalPath;
    @XmlAttribute(name = "mgmtId")
    protected String mgmtId;

    /**
     * Gets the value of the siteId property.
     * 
     * @return
     *     possible object is
     *     {@link CTId }
     *     
     */
    public CTId getSiteId() {
        return siteId;
    }

    /**
     * Sets the value of the siteId property.
     * 
     * @param value
     *     allowed object is
     *     {@link CTId }
     *     
     */
    public void setSiteId(CTId value) {
        this.siteId = value;
    }

    /**
     * Gets the value of the siteDescriptorId property.
     * 
     * @return
     *     possible object is
     *     {@link CTId }
     *     
     */
    public CTId getSiteDescriptorId() {
        return siteDescriptorId;
    }

    /**
     * Sets the value of the siteDescriptorId property.
     * 
     * @param value
     *     allowed object is
     *     {@link CTId }
     *     
     */
    public void setSiteDescriptorId(CTId value) {
        this.siteDescriptorId = value;
    }

    /**
     * Gets the value of the siteLocaleDescriptorId property.
     * 
     * @return
     *     possible object is
     *     {@link CTId }
     *     
     */
    public CTId getSiteLocaleDescriptorId() {
        return siteLocaleDescriptorId;
    }

    /**
     * Sets the value of the siteLocaleDescriptorId property.
     * 
     * @param value
     *     allowed object is
     *     {@link CTId }
     *     
     */
    public void setSiteLocaleDescriptorId(CTId value) {
        this.siteLocaleDescriptorId = value;
    }

    /**
     * Gets the value of the channelDescriptorId property.
     * 
     * @return
     *     possible object is
     *     {@link CTId }
     *     
     */
    public CTId getChannelDescriptorId() {
        return channelDescriptorId;
    }

    /**
     * Sets the value of the channelDescriptorId property.
     * 
     * @param value
     *     allowed object is
     *     {@link CTId }
     *     
     */
    public void setChannelDescriptorId(CTId value) {
        this.channelDescriptorId = value;
    }

    /**
     * Gets the value of the channelLocaleDescriptorId property.
     * 
     * @return
     *     possible object is
     *     {@link CTId }
     *     
     */
    public CTId getChannelLocaleDescriptorId() {
        return channelLocaleDescriptorId;
    }

    /**
     * Sets the value of the channelLocaleDescriptorId property.
     * 
     * @param value
     *     allowed object is
     *     {@link CTId }
     *     
     */
    public void setChannelLocaleDescriptorId(CTId value) {
        this.channelLocaleDescriptorId = value;
    }

    /**
     * Gets the value of the contentTypeAssociation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the contentTypeAssociation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContentTypeAssociation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CTSiteContentTypeAssociation }
     * 
     * 
     */
    public List<CTSiteContentTypeAssociation> getContentTypeAssociation() {
        if (contentTypeAssociation == null) {
            contentTypeAssociation = new ArrayList<CTSiteContentTypeAssociation>();
        }
        return this.contentTypeAssociation;
    }

    /**
     * Gets the value of the adhocReferences property.
     * 
     * @return
     *     possible object is
     *     {@link CTAdhocReferences }
     *     
     */
    public CTAdhocReferences getAdhocReferences() {
        return adhocReferences;
    }

    /**
     * Sets the value of the adhocReferences property.
     * 
     * @param value
     *     allowed object is
     *     {@link CTAdhocReferences }
     *     
     */
    public void setAdhocReferences(CTAdhocReferences value) {
        this.adhocReferences = value;
    }

    /**
     * Gets the value of the acl property.
     * 
     * @return
     *     possible object is
     *     {@link CTAcl }
     *     
     */
    public CTAcl getAcl() {
        return acl;
    }

    /**
     * Sets the value of the acl property.
     * 
     * @param value
     *     allowed object is
     *     {@link CTAcl }
     *     
     */
    public void setAcl(CTAcl value) {
        this.acl = value;
    }

    /**
     * Gets the value of the vcmId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVcmId() {
        return vcmId;
    }

    /**
     * Sets the value of the vcmId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVcmId(String value) {
        this.vcmId = value;
    }

    /**
     * Gets the value of the vcmStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVcmStatus() {
        return vcmStatus;
    }

    /**
     * Sets the value of the vcmStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVcmStatus(String value) {
        this.vcmStatus = value;
    }

    /**
     * Gets the value of the vcmName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVcmName() {
        return vcmName;
    }

    /**
     * Sets the value of the vcmName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVcmName(String value) {
        this.vcmName = value;
    }

    /**
     * Gets the value of the vcmLogicalPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVcmLogicalPath() {
        return vcmLogicalPath;
    }

    /**
     * Sets the value of the vcmLogicalPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVcmLogicalPath(String value) {
        this.vcmLogicalPath = value;
    }

    /**
     * Gets the value of the mgmtId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMgmtId() {
        return mgmtId;
    }

    /**
     * Sets the value of the mgmtId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMgmtId(String value) {
        this.mgmtId = value;
    }

}
