<?php

namespace Japode\PostType\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * JPPostTypeAttrRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JPPostTypeAttrRepository extends EntityRepository {

    /**
     * Finds the Max Order of Post Type Attribute with its email
     *
     * @param string $email
     * @return JPUser
     */
    public function maxOrderByPostTypeId($postTypeId) {

        $qb = $this->createQueryBuilder('p');
        return $qb->select('MAX(p.position) AS max_position')
                        ->innerJoin('p.postType', 'pt')
                        ->where($qb->expr()->eq('pt.id', ':postTypeId'))
                        ->setParameter('postTypeId', $postTypeId)
                        ->getQuery()
                        ->getOneOrNullResult();
        
    }

}
