<?php

namespace Japode\PostType\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * JPPostTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JPPostTypeRepository extends EntityRepository {

    /**
     * Finds a postType with its name
     *
     * @param string $name
     * @return JPPostType
     */
    public function findByName($name) {

        $qb = $this->createQueryBuilder('pt');
        return $qb->where($qb->expr()->eq('pt.name', ':name'))
                        ->setParameter('name', $name)
                        ->getQuery()
                        ->getOneOrNullResult();
    }

}
